// client/src/components/ScoreBoard.svelte
<script>
import { GAME_MODES } from '../../../shared/messages.js';
import { gameConfig, myId, scores } from '../stores/game.js';

$: mode = $gameConfig.mode;
$: isTDM = mode === GAME_MODES.TEAM_DEATHMATCH;
$: isCTF = mode === GAME_MODES.CAPTURE_THE_FLAG;
$: isInfection = mode === GAME_MODES.INFECTION;
$: isDomination = mode === GAME_MODES.DOMINATION;
</script>

<div class="scoreboard">
  {#if isDomination}
    {#each $scores as team}
      <div class="team-row team-{team.team}">
        <span class="team-label">{team.team.toUpperCase()}</span>
        <span class="team-points">🏆 {team.points}</span>
        <div class="player-list">
          {#each team.players as p}
            <span class="player" class:is-me={p.id === $myId} class:dead={p.isAlive === false}>
              {p.username} {p.kills}/{p.deaths}
              {#if p.hp != null}
                <span class="hp">{p.isAlive === false ? '☠' : `♥${p.hp}`}</span>
              {/if}
            </span>
          {/each}
        </div>
      </div>
    {/each}
  {:else if isCTF}
    {#each $scores as team}
      <div class="team-row team-{team.team}">
        <span class="team-label">{team.team.toUpperCase()}</span>
        <span class="team-captures">🚩 {team.captures}</span>
        <div class="player-list">
          {#each team.players as p}
            <span class="player" class:is-me={p.id === $myId} class:dead={p.isAlive === false}>
              {p.username}{p.hasFlag ? ' 🚩' : ''} {p.kills}/{p.deaths}
            </span>
          {/each}
        </div>
      </div>
    {/each}
  {:else if isInfection}
    {#each $scores as group}
      <div class="inf-group inf-{group.team}">
        <span class="inf-label">{group.team === 'infected' ? '🧟 INFECTED' : '🧍 SURVIVORS'}</span>
        <span class="inf-count">{group.count}</span>
        <div class="player-list">
          {#each group.players as p}
            <span class="player" class:is-me={p.id === $myId}>
              {p.username}{group.team === 'infected' ? ` (${p.kills})` : ''}
            </span>
          {/each}
        </div>
      </div>
    {/each}
  {:else if isTDM}
    {#each $scores as team}
      <div class="team-row team-{team.team}">
        <span class="team-label">{team.team.toUpperCase()}</span>
        <span class="team-kills">{team.kills}</span>
        <div class="player-list">
          {#each team.players as p}
            <span class="player" class:is-me={p.id === $myId} class:dead={p.isAlive === false}>
              {p.username} {p.kills}/{p.deaths}
              {#if p.hp != null}
                <span class="hp">{p.isAlive === false ? '☠' : `♥${p.hp}`}</span>
              {/if}
            </span>
          {/each}
        </div>
      </div>
    {/each}
  {:else}
    {#each $scores as p, i}
      <div class="score-row" class:is-me={p.id === $myId} class:dead={p.isAlive === false}>
        <span class="rank">#{i + 1}</span>
        <span class="name">{p.username}</span>
        {#if p.hp != null}
          <span class="hp">{p.isAlive === false ? '☠' : `♥${p.hp}`}</span>
        {/if}
        <span class="kd">{p.kills}<span class="sep">/</span>{p.deaths}</span>
      </div>
    {/each}
  {/if}
</div>

<style>
  .scoreboard {
    background: rgba(0,0,0,0.7);
    border: 1px solid rgba(255,255,255,0.1);
    border-radius: 8px;
    padding: 8px;
    font-size: 13px;
    min-width: 160px;
  }

  .score-row {
    display: flex;
    align-items: center;
    gap: 6px;
    padding: 3px 0;
    color: #ccc;
  }
  .score-row.is-me { color: #fff; font-weight: 700; }
  .rank { color: #666; width: 22px; }
  .name { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .kd { color: #aaa; font-variant-numeric: tabular-nums; }
  .sep { color: #555; margin: 0 2px; }
  .hp { color: #ff7a7a; font-size: 11px; font-variant-numeric: tabular-nums; }
  .score-row.dead, .player.dead { opacity: 0.5; }

  .team-row { padding: 4px 0; }
  .team-row.team-red .team-label { color: #ff5252; }
  .team-row.team-blue .team-label { color: #448aff; }
  .team-label { font-weight: 700; font-size: 11px; letter-spacing: 1px; }
  .team-kills { float: right; font-weight: 700; font-size: 15px; }
  .team-captures { float: right; font-weight: 700; font-size: 15px; }
  .team-points { float: right; font-weight: 700; font-size: 15px; }
  .player-list { display: flex; flex-direction: column; gap: 2px; margin-top: 3px; }
  .player { font-size: 12px; color: #bbb; }
  .player.is-me { color: #fff; font-weight: 700; }

  .inf-group { padding: 4px 0; }
  .inf-label { font-weight: 700; font-size: 11px; letter-spacing: 1px; }
  .inf-count { float: right; font-weight: 700; font-size: 15px; }
  .inf-group.inf-infected .inf-label { color: #ff5252; }
  .inf-group.inf-survivors .inf-label { color: #00c853; }
</style>

// mobile/src/components/ScoreBoard.tsx
/**
 * In-game scoreboard overlay. Mirrors client/src/components/ScoreBoard.svelte:
 * one layout per game mode (Domination / CTF / Infection / TDM / FFA) showing
 * who's leading. Driven by the `scores` array the server pushes in GAME_STATE.
 */
import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { GAME_MODES } from 'shared/messages.js';
import { useGameStore } from '../stores/game.js';

// Score entries carry mode-specific fields the base ScoreEntry type doesn't
// enumerate (points/captures/count/hasFlag); read them loosely.
type AnyScore = Record<string, any>;

export default function ScoreBoard() {
  const { scores, myId, gameConfig } = useGameStore();
  const mode = gameConfig.mode;
  const list = scores as AnyScore[];

  const renderPlayer = (p: AnyScore, extra?: string) => (
    <Text
      key={p.id}
      style={[
        styles.player,
        p.id === myId && styles.playerMe,
        p.isAlive === false && styles.dead,
      ]}>
      {p.username}
      {extra ?? ''} {p.kills}/{p.deaths}
      {p.hp != null ? (p.isAlive === false ? ' ☠' : ` ♥${p.hp}`) : ''}
    </Text>
  );

  let body: React.ReactNode;

  if (mode === GAME_MODES.DOMINATION) {
    body = list.map(team => (
      <View key={team.team} style={styles.teamRow}>
        <View style={styles.teamHeader}>
          <Text style={[styles.teamLabel, teamColor(team.team)]}>
            {String(team.team).toUpperCase()}
          </Text>
          <Text style={styles.teamScore}>🏆 {team.points ?? 0}</Text>
        </View>
        <View style={styles.playerList}>
          {(team.players ?? []).map((p: AnyScore) => renderPlayer(p))}
        </View>
      </View>
    ));
  } else if (mode === GAME_MODES.CAPTURE_THE_FLAG) {
    body = list.map(team => (
      <View key={team.team} style={styles.teamRow}>
        <View style={styles.teamHeader}>
          <Text style={[styles.teamLabel, teamColor(team.team)]}>
            {String(team.team).toUpperCase()}
          </Text>
          <Text style={styles.teamScore}>🚩 {team.captures ?? 0}</Text>
        </View>
        <View style={styles.playerList}>
          {(team.players ?? []).map((p: AnyScore) =>
            renderPlayer(p, p.hasFlag ? ' 🚩' : ''),
          )}
        </View>
      </View>
    ));
  } else if (mode === GAME_MODES.INFECTION) {
    body = list.map(group => (
      <View key={group.team} style={styles.teamRow}>
        <View style={styles.teamHeader}>
          <Text
            style={[
              styles.teamLabel,
              { color: group.team === 'infected' ? '#ff5252' : '#00c853' },
            ]}>
            {group.team === 'infected' ? '🧟 INFECTED' : '🧍 SURVIVORS'}
          </Text>
          <Text style={styles.teamScore}>{group.count ?? 0}</Text>
        </View>
        <View style={styles.playerList}>
          {(group.players ?? []).map((p: AnyScore) => (
            <Text
              key={p.id}
              style={[styles.player, p.id === myId && styles.playerMe]}>
              {p.username}
              {group.team === 'infected' ? ` (${p.kills})` : ''}
            </Text>
          ))}
        </View>
      </View>
    ));
  } else if (mode === GAME_MODES.TEAM_DEATHMATCH) {
    body = list.map(team => (
      <View key={team.team} style={styles.teamRow}>
        <View style={styles.teamHeader}>
          <Text style={[styles.teamLabel, teamColor(team.team)]}>
            {String(team.team).toUpperCase()}
          </Text>
          <Text style={styles.teamScore}>{team.kills ?? 0}</Text>
        </View>
        <View style={styles.playerList}>
          {(team.players ?? []).map((p: AnyScore) => renderPlayer(p))}
        </View>
      </View>
    ));
  } else {
    // FFA: flat, ranked list.
    body = list.map((p, i) => (
      <View
        key={p.id}
        style={[styles.scoreRow, p.isAlive === false && styles.dead]}>
        <Text style={styles.rank}>#{i + 1}</Text>
        <Text
          style={[styles.name, p.id === myId && styles.nameMe]}
          numberOfLines={1}>
          {p.username}
        </Text>
        {p.hp != null && (
          <Text style={styles.hp}>{p.isAlive === false ? '☠' : `♥${p.hp}`}</Text>
        )}
        <Text style={styles.kd}>
          {p.kills}/{p.deaths}
        </Text>
      </View>
    ));
  }

  return <View style={styles.scoreboard}>{body}</View>;
}

function teamColor(team: string) {
  if (team === 'red') return { color: '#ff5252' };
  if (team === 'blue') return { color: '#448aff' };
  return { color: '#bbb' };
}

const styles = StyleSheet.create({
  scoreboard: {
    backgroundColor: 'rgba(0,0,0,0.78)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 8,
    padding: 8,
    minWidth: 180,
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 3,
  },
  rank: { color: '#666', width: 26, fontSize: 13 },
  name: { flex: 1, color: '#ccc', fontSize: 13 },
  nameMe: { color: '#fff', fontWeight: '700' },
  kd: { color: '#aaa', fontSize: 13, fontVariant: ['tabular-nums'] },
  hp: { color: '#ff7a7a', fontSize: 11, marginHorizontal: 6 },
  dead: { opacity: 0.5 },
  teamRow: { paddingVertical: 4 },
  teamHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  teamLabel: { fontWeight: '700', fontSize: 11, letterSpacing: 1 },
  teamScore: { fontWeight: '700', fontSize: 15, color: '#fff' },
  playerList: { marginTop: 3, gap: 2 },
  player: { fontSize: 12, color: '#bbb' },
  playerMe: { color: '#fff', fontWeight: '700' },
});
